name: Pants build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.12
      uses: actions/setup-python@v3
      with:
        python-version: "3.12"
    - name: Initialize Pants
      uses: pantsbuild/actions/init-pants@v8
      with:
        # cache0 makes it easy to bust the cache if needed
        gha-cache-key: cache0-py${{ matrix.python_version }}
        named-caches-hash: ${{ hashFiles('lockfiles/*.json', '**/something-else.lock') }}
    - name: Check BUILD files
      run: |
        pants tailor --check update-build-files --check ::
    - name: Lint and typecheck
      run: |
        pants lint check ::
    - name: Test
      run: |
        pants test ::
    - name: Package / Run
      run: |
        # We also smoke test that our release process will work by running `package`.
        pants package ::
        pants run :tycoon